FROM debian:bullseye

ENV TZ=America/New_York
ENV PATH=/go/bin:$PATH
ENV GOROOT=/go
ENV GOPATH=/src/go


RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone &&\
    mkdir /go &&\
    mkdir -p /src/go &&\
    apt update &&\
    apt -y install build-essential &&\
    apt -y install gdal-bin gdal-data libgdal-dev &&\
    apt -y install wget &&\
    apt -y install curl &&\
    wget https://golang.org/dl/go1.20.10.linux-arm64.tar.gz -P / &&\
    tar -xvzf /go1.20.10.linux-arm64.tar.gz -C / &&\
    apt -y install git &&\  
    apt -y install unzip &&\
    apt -y install locales locales-all

COPY ./docker/entry.sh /
RUN chmod 755 /entry.sh
ENTRYPOINT [ "/entry.sh" ]    
     
    
  
 
